export const SHOP_LIST_REQUEST = 'SHOP_LIST_REQUEST';
export const SHOP_LIST_SUCCESS = 'SHOP_LIST_SUCCESS';
export const SHOP_LIST_FAIL = 'SHOP_LIST_FAIL';

export const SHOP_DETAILS_REQUEST = 'SHOP_DETAILS_REQUEST';
export const SHOP_DETAILS_SUCCESS = 'SHOP_DETAILS_SUCCESS';
export const SHOP_DETAILS_FAIL = 'SHOP_DETAILS_FAIL';


export const SHOP_SAVE_REQUEST = 'SHOP_SAVE_REQUEST';
export const SHOP_SAVE_SUCCESS = 'SHOP_SAVE_SUCCESS';
export const SHOP_SAVE_FAIL = 'SHOP_SAVE_FAIL';

export const SHOP_DELETE_REQUEST = 'SHOP_DELETE_REQUEST';
export const SHOP_DELETE_SUCCESS = 'SHOP_DELETE_SUCCESS';
export const SHOP_DELETE_FAIL = 'SHOP_DELETE_FAIL';